### ISSUE TITLE
Questions about Fig.5.

### ISSUE THREAD

**Issue by imlixinyang** [ShenYujun/HiGAN#1]
Hello, you've did a great work! 
I've read your paper but take a lot of time to think about fig.5, So I wonder if you can help me.
There is my question: In the bottom figure, it seems like the height of patches are different in the left one and right one, so I guess it means the area of segment mask for specific label in images. But it becomes almost the same in the middle, why? Did I made a mistake?

**Comment by limbo0000** [comment]
Thanks for reading.
The bottom of Fig.5 shows the transformation **from left to right**. Actually, after transforming the living room to the bedroom, we mainly focus on what objects the transformed would become next.
That is why it seems the same in the middle.
